#!/bin/bash
# ============================================================
# Cloudflare Pages Build Script — Admin Frontend
# ============================================================
# Set the following environment variables in Cloudflare Pages:
#   MAPBOX_TOKEN   → Your Mapbox public token (secret)
#   API_URL        → Backend URL (e.g. https://api.intercity-van.com)
#   TENANT_ID      → Your tenant ID
# ============================================================

echo "🔧 Generating env.js from Cloudflare environment variables..."

cat > env.js <<EOF
// ⚠️ AUTO-GENERATED by build.sh — DO NOT EDIT MANUALLY
// This file is generated at build time from Cloudflare Pages environment variables.
window.ENV = {
  API_URL: "${API_URL:-http://localhost:5000}",
  MAPBOX_TOKEN: "${MAPBOX_TOKEN:-YOUR_MAPBOX_TOKEN_HERE}",
  TENANT_ID: "${TENANT_ID:-tenant-default-001}"
};
EOF

echo "✅ env.js generated:"
cat env.js
